# Generated by Django 5.1.3 on 2024-12-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdsdailydata',
            name='value',
            field=models.FloatField(verbose_name='Custom Value'),
        ),
        migrations.AlterField(
            model_name='cdsdailydataimport',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cdspreset',
            name='actual_qty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cdspreset',
            name='qty_ulccs',
            field=models.FloatField(),
        ),
    ]
